CREATE TABLE Users (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Email TEXT NOT NULL UNIQUE,
  PasswordHash TEXT NOT NULL,
  FirstNameEncrypted TEXT NOT NULL,
  MiddleNameEncrypted TEXT NULL,
  LastNameEncrypted TEXT NOT NULL,
  CreatedAtUtc TEXT NOT NULL
);

CREATE TABLE Categories (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL
);

CREATE TABLE Suppliers (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  ContactName TEXT NOT NULL,
  ContactEmail TEXT NOT NULL,
  SupplyHistory TEXT NULL
);

CREATE TABLE Products (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Sku TEXT NOT NULL UNIQUE,
  StockLevel INTEGER NOT NULL,
  Price DECIMAL(18,2) NOT NULL,
  CategoryId INTEGER NOT NULL,
  IntegrityHash TEXT NOT NULL,
  FOREIGN KEY(CategoryId) REFERENCES Categories(Id)
);
